{
 "title": "Chain",
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "45s",
 "panels": [
  {
   "title": "Blocks Won",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "alias": "$tag_miner",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "miner" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "chain.election",
     "query": "SELECT count(\"value\") FROM \"chain.election\" WHERE $timeFilter -10m GROUP BY time($__interval), \"miner\" fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "count"
       },
       { "params": [ "20" ], "type": "moving_average" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Total Power",
   "type": "graph",
   "gridPos": { "h": 4, "w": 8, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "measurement": "chain.power",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Avg Blocktime",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 8, "y": 9 },
   "format": "s",
   "valueName": "avg",
   "targets": [
    {
     "measurement": "chain.blocktime",
     "query": "SELECT difference(mean(\"value\")) FROM \"chain.blocktime\" WHERE $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "difference"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Network Storage",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 12, "y": 9 },
   "format": "bytes",
   "valueName": "current",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT sum(\"value\") FROM \"chain.miner_power\" WHERE $timeFilter GROUP BY time(45s)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Blocks In Tipset",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 8, "x": 16, "y": 9 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" }
     ],
     "measurement": "chain.election",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Block Height",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 13 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "measurement": "chain.height",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Last Blocktime",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 4, "y": 13 },
   "format": "s",
   "valueName": "current",
   "targets": [
    {
     "measurement": "chain.blocktime",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "difference"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Avg Gas Price",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 8, "y": 13 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "chain.message_gasprice",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Avg Message Size",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 12, "y": 13 },
   "format": "decbytes",
   "valueName": "avg",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "chain.message_size",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Avg Blockheader Size",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 16, "y": 13 },
   "format": "bytes",
   "valueName": "avg",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "chain.blockheader_size",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Avg Messages in Tipset",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 20, "y": 13 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "chain.message_count",
     "query": "SELECT \"value\" FROM \"chain.message_count\" WHERE $timeFilter ",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Head Updated",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 16 },
   "format": "dateTimeFromNow",
   "valueName": "current",
   "targets": [
    {
     "measurement": "chain.blocktime",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       { "params": [ "*1000" ], "type": "math" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Tipsets",
   "type": "graph",
   "gridPos": { "h": 3, "w": 16, "x": 4, "y": 16 },
   "yaxes": [
    { "format": "s", "label": "Time between tipsets" }
   ],
   "targets": [
    {
     "alias": "Block Time",
     "measurement": "chain.blocktime",
     "query": "SELECT difference(\"value\") FROM \"chain.blocktime\" WHERE $timeFilter",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "difference"
       }
      ]
     ]
    },
    {
     "alias": "Null Blocks",
     "measurement": "chain.height",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "difference"
       },
       { "params": [ "-1" ], "type": "math" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Pledge Collateral",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 20, "y": 16 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "measurement": "chain.pledge_collateral",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Top Power Table",
   "type": "table",
   "gridPos": { "h": 21, "w": 4, "x": 0, "y": 19 },
   "targets": [
    {
     "measurement": "chain.miner_power",
     "query": "SELECT top(\"value\", \"miner\", 20) as \"power\" FROM \"chain.miner_power\" WHERE $timeFilter",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Top Miner Power",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 4, "y": 19 },
   "yaxes": [
    { "format": "bytes", "label": "Power" }
   ],
   "targets": [
    {
     "alias": "$tag_miner",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "miner" ], "type": "tag" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "chain.miner_power",
     "query": "SELECT mean(\"value\") FROM \"chain.miner_power\" WHERE $timeFilter GROUP BY time($__interval), \"miner\" fill(previous)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [
         "\"miner\",20"
        ],
        "type": "top"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Chain Table",
   "type": "table",
   "gridPos": { "h": 21, "w": 8, "x": 16, "y": 19 },
   "targets": [
    {
     "measurement": "chain.height",
     "query": "SELECT \"value\", \"tipset\" FROM \"chain.height\" WHERE $timeFilter",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Pledge Collateral",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 4, "y": 27 },
   "yaxes": [
    { "format": "short", "label": "EPK" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "chain.pledge_collateral",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Miners on Chain",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 4, "y": 33 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "chain.miner_power",
     "query": "SELECT count(\"value\") FROM \"chain.miner_power\" WHERE $timeFilter GROUP BY time($__interval)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "count"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Actor Messages Method",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 40 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "Adr $tag_actor | Md $tag_method",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "actor" ], "type": "tag" },
      { "params": [ "method" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "chain.message_count",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Actor Messages Method With Exitcode",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 40 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "Adr $tag_actor | Md $tag_method | Ex $tag_exitcode",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "method" ], "type": "tag" },
      { "params": [ "exitcode" ], "type": "tag" },
      { "params": [ "actor" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "chain.message_count",
     "query": "SELECT sum(\"value\") FROM \"chain.message_count\" WHERE $timeFilter GROUP BY time($__interval), \"method\", \"exitcode\", \"actor\" fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "count"
       }
      ]
     ]
    }
   ]
  }
 ]
}