#!/usr/bin/env sh

set -o xtrace

export TRUST_PARAMS=1
tag=${TAG:-debug}

go run -tags=$tag ./cmd/epik-seed pre-seal --sector-size 2KiB --num-sectors 2
go run -tags=$tag ./cmd/epik-seed genesis new localnet.json
go run -tags=$tag ./cmd/epik-seed genesis add-miner localnet.json ~/.genesis-sectors/pre-seal-t01000.json
go run -tags=$tag ./cmd/epik daemon --epik-make-genesis=devel.gen --genesis-template=localnet.json --bootstrap=false
